name: "FRP Proxy Client for HassIO"
description: "This tool can be used to setup a FRP proxy to bypass portfowarding"
version: "1.0.1"
slug: "frp_client"
init: false
network: host
startup: services
init: false
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
host_network: true
schema:
  serverip: str
  serverport: int
  token: str?
  localport : int
  remoteport: int
  encryption: bool?
  compression: bool?
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
